### ISSUE TITLE
Matrix Chat

### ISSUE THREAD

**Issue by TheOPtimal** [RootMyTV/RootMyTV.github.io#10]
It would be great if there was a Matrix chat for this project. Matrix is an open chat protocol, with the most famous and featureful client being Element. Its like IRC for the 21st century.

Many people, including me have dropped Discord in favour of Matrix, so can a room or space be made for Matrix Users?

You can sign up at [element.io](https://element.io)

P.S.
Spaces are similar to discord servers
Rooms are similar to discord channels, but rooms can be independent of spaces
Matrix rooms can be bridged to discord channels

**Comment by Informatic** [comment]
The future is now: https://matrix.to/#/#openlgtv:netserve.live

:)

**Comment by Informatic** [comment]
Matrix chat link has been added to README.
