### ISSUE TITLE
Is this reverseable?

### ISSUE THREAD

**Issue by upintheairsheep** [RootMyTV/RootMyTV.github.io#11]
Can I fully "unbrew" my TV if I want to?

**Comment by Informatic** [comment]
Yeah. This is not very well documented, but all the paths we touch are listed here:
https://github.com/webosbrew/webos-homebrew-channel/issues/11

**Comment by Informatic** [comment]
A not on how to reverse this has been added in [FAQ section in README](https://github.com/RootMyTV/RootMyTV.github.io#how-do-i-get-rid-of-this).
