### ISSUE TITLE
Any method to reroot my LG TV? or alternative way to Hard-Reset

### ISSUE THREAD

**Issue by p2pdownsbrz** [RootMyTV/RootMyTV.github.io#139]
Hi, is there any way to overwrite the root or jailbreak, I already did the jailbreak on the TV, everything went fine, but when trying to update the chromium through overlays it ended up going very wrong, now due to my inexperience and my own mistakes when using the root I can no longer access ssh, telnet and apps, however, it still turns on and works hdmi-CEC with firetv, and connects to the internet via ethernet, and when I try to root, the confirmation window appears if you want to allow rootmytv access the TV, meanwhile the browser shows the following log:
0.Connecting...
1. Connected, registering... Accept prompt on the TV.
2. Registered - looking for vulnerable apps...
3. Found com.webos.app.acrcard
3. Found com.webos.app.alibaba
3. Found com.webos.app.facebooklogin
3. Launching com.webos.app.alibaba...
3. Launch result: {"type":"response","id":"1707060559212","payload":{"returnValue":true,"id":"com.webos.app.alibaba","sessionId" :"Y29tLndlYm9zLmFwcC5hbGliYWJh"}}
The TV does not restart after this. I'm wondering if it's possible to modify the rootmytv script to reinstall the webosbrew app and root access or be able to activate telnet or ssh again, the webosbrew apps disappeared and therefore I couldn't access any app, I can only use the hdmi function, menu TV settings won't open, so I couldn't initiate a hard reset... . I'm aware that the error was completely mine, but I'd be grateful if anyone has any solution or method for me to at least try a hard reset... TV model: 49UK6310PSE, I don't know what was the last WebOS update I did before making this mess .
(I'm using an online translator, English is not my native language, so if you can understand it, please ignore the writing errors).

**Comment by throwaway96** [comment]
How exactly did you try to "update the chromium through overlays"?


What is the firmware version ("software version") of the TV?

You should be able to use an [SSAP client](https://github.com/throwaway96/webos-ssap-web) to manually do the same things RootMyTV does.

That model uses an LM18A SoC, and (the relevant part of) the OTAID is W18A. Your TV will be vulnerable to [crashd](https://gist.github.com/throwaway96/e811b0f7cc2a705a5a476a8dfa45e09f) since LG has not yet released any patched firmware for W18A.

**Comment by p2pdownsbrz** [comment]
First of all, thank you very much for responding, and you responded very quickly!
I updated it almost 3 years ago, I think via USB, but when I looked on the website, there was no firmware available for my TV model 49UK6310PSE
I don't remember all the steps I followed, but I got some instructions similar to those on this website https://www.webosbrew.org/pages/filesystem-overlays.html#keeping-overlays-persistent, I made one or more init scripts. I don't remember which version of Chromium I used, but I think I must have used the wrong Arm architecture, I was very noob, I think it's been over 2 years since I did this, so I don't remember in detail.
I tested this SSAP demo on a simple http server, it worked, the TV screen appeared in the laptop's web browser.
github.com/throwaway96/webos-ssap-web

I don't know how to use CLI commands via SSAP, the TV screen was mirrored on the laptop's browser, will I need to edit any of the files to be able to pass the commands? would it be the luna-send commands? I believe that if I remove the init scripts the TV returns to normal, but I don't know how to do it. I will read the links you sent more carefully now. Thank you very much. Any additional tips, specific or vague, are very welcome. I'm a linux user (Distro based on archLinux), so if you have any .sh script that speeds up the removal of my changes, or one that allows me to regain telnet or ssh access, or a shell via ssap, any tips or additional instructions , are very welcome. , which appear to be disabled. I checked with NMAP. my main goal is to remove the init scripts, and then reinstall rootmytv/webosbrew.

**Comment by throwaway96** [comment]
Have you tried to install Developer Mode from the LG store?

**Comment by throwaway96** [comment]
Well, you're certainly in an interesting situation. It would help to know exactly what you installed, what version of RootMyTV you used, and what version of Homebrew Channel you had installed.

If I understand correctly, you don't want to do a factory reset. But you could, right? Or is that broken as well?

It might be easier to help you on Discord. I don't have an invite link right now, but there's one on [webosbrew.org](https://www.webosbrew.org/).

**Comment by p2pdownsbrz** [comment]
@throwaway96  rootmytv v2 before you put the .html warning about patched tv, I can't do a factory reset, because I don't have access to the configuration panel or the configuration app, when the configuration window appears, no text appears and no I can interact, and it closes. I would prefer to keep root, really. But my priority is to get the TV working normally again, with or without root enabled.

**Comment by p2pdownsbrz** [comment]
I tested it, everything worked normally again!
Thanks again, I forgot to close the issue.
 :)
