### ISSUE TITLE
Brightness control

### ISSUE THREAD

**Issue by rahmedd** [RootMyTV/RootMyTV.github.io#14]
I'm using a the LG UP7000 TV as a monitor. Because it's not technically a monitor it doesn't have support for brightness control or DDC/CI. I would like to be able to easily change the brightness without using the remote and webOS's slow and complicated UI. Any ideas on how I could achieve this? Is there a way I can execute some script on the TV over SSH every time I need to change the brightness?

**Comment by Informatic** [comment]
Yes, that should be perfectly doable over SSH. (or HTTP/TCP if you expose your own service on the TV)

You can use common debugging tools like `ls-monitor` to see what brightness changing using the remote actually do - here's some basic reference: https://www.webosbrew.org/pages/luna-service-bus.html

On my TV (2017 LCD, webOS 3.8) this will adjust the brightness:
```sh
luna-send -n 1 'luna://com.webos.settingsservice/setSystemSettings' '{"settings":{"backlight":95},"category":"picture"}'
```

**Comment by rahmedd** [comment]
I'll give it a try, thanks Informatic!

**Comment by Informatic** [comment]
Closing, reopen in case you still need something.
