### ISSUE TITLE
The process stops with Denied method call "download"

### ISSUE THREAD

**Issue by Martin-Laclaustra** [RootMyTV/RootMyTV.github.io#15]
The screen shows the following message:
```
start-devmode.sh: Downloading from https://rootmy.tv/files/stage3.sh...
err: {"returnValue":false,"errorCode":-1,"errorText":"Denied method call \"download\" for category \"/\""}
```

Thanks for your efforts.

**Comment by kjeller** [comment]
You can refer to [this link](https://github.com/RootMyTV/RootMyTV.github.io/issues/2) and check if your version is currently supported by rootmy.tv.

**Comment by Martin-Laclaustra** [comment]
@kjeller Thank you. I will check it out.
Downgrading seems like a complex procedure... Can you advice a tutorial to follow? Thanks again!

**Comment by kjeller** [comment]
I followed [this guide](https://www.avsforum.com/threads/guide-lg-webos-tvs-firmware-downgrade-advanced-users-only.3217168/) and I downloaded an older version of my firmware from the openlgtv/fw-downgrade channel. If you are lucky, an older version for your TV might also be available from [official LG sources](https://www.lg.com/support/software-firmware).

**Comment by denimjeans** [comment]
I had the same, and followed this guide, it is really simple, but not sure if that's safe:
1. download the desired firmware version
2. open https://webosapp.club/downgrade/ with the LG webbrowser
3. that's 

here is the [link](https://www.avforums.com/threads/lg-oled-c8-owners-and-discussion.2162797/page-636#post-29598721)

**Comment by DpunktKpunkt** [comment]
Thank you @denimjeans you made my day!

Here at the russian webos forum is a collection with tons of links to all sorts of older firmware images for nearly every webOS TV: http://webos-forums.ru/post23624.html#p23624

**Comment by Informatic** [comment]
PSA: RootMyTV v2 release is planned for around 2022/01/14 18:00 UTC (this Friday)

This will be compatible with all current webOS versions between 3.4 and 6.2 (up to the latest released ones), and shall alleviate any issues reported here.

**Comment by Informatic** [comment]
RootMyTV v2 is out now.
