### ISSUE TITLE
Running binaries (copies via SCP) such as htop etc does not work

### ISSUE THREAD

**Issue by denimjeans** [RootMyTV/RootMyTV.github.io#16]
first of all, thanks for the wonderful easy rootmy.tv, after downgrading my LG C8 LLA it worked perfectly. Nice job!
my problem - not really related to rootmy.tv: 
I have tried to copy some binaries from my rpi4 via SCP to my LG TV (to /home/root/). when I try to execute them, like with ./htop I receive "file not found". If I do "ls" the files are there...
If I copy any binary from LG to my RPI4, like /usr/bin/aplay, it works on the RPI4, but not otherway around. I am trying to understand why? Are the binaries signed by chance or similar? 
/proc/cpuinfo:
RPI has  ARMv7 Processor rev 4 (v7l)
LG has  ARMv7 Processor rev 2 (v7l)

**Comment by DavidBuchanan314** [comment]
Chances are, you're running into issues with dynamic linking.

You could either:

a) Find a staticly-linked version (or compile your own)
b) Compile your own version, linked with the correct libraries for your TV, using https://github.com/webosbrew/meta-lg-webos-ndk
c) Copy over all the library dependencies from your pi (you can find them using `ldd`), and point ld.so at them by specifying LD_LIBRARY_PATH
d) Use https://github.com/intoli/exodus
