### ISSUE TITLE
[webOS 3.9.0] Halts on Stage 1

### ISSUE THREAD

**Issue by kubbur** [RootMyTV/RootMyTV.github.io#20]
the script halts after that and screensaver turns on later

![20220114_202211](https://user-images.githubusercontent.com/816497/149585396-e97fbf89-e295-41d4-92bc-df6c87b333bc.jpg)
![20220114_192445](https://user-images.githubusercontent.com/816497/149585402-4a69df7a-6703-4a8b-96ab-285578279e51.jpg)

**Comment by Informatic** [comment]
Yeah, definitely something that can be fixed fairly easily. We'll see how we can handle this.

**Comment by crookshanked** [comment]
Seconding this issue. 
3.9.0-62804 deadlocks2-dudhwa
Run it, gray screen with the squares on it, then a black screen. Enter button brings back to the page. The browser mentions stage 1.

**Comment by kubbur** [comment]
> Seconding this issue. 3.9.0-62804 deadlocks2-dudhwa Run it, gray screen with the squares on it, then a black screen. Enter button brings back to the page. The browser mentions stage 1. I don't even see the payload stuff like the above.

i dont remember exacly but i pushed some button the second time i tried it and then the payload stuff appeared

**Comment by Informatic** [comment]
This should be fixed now, can you verify this?

**Comment by kubbur** [comment]
Works, that was quick, thank you 😊

**Comment by Informatic** [comment]
You can add these to #18 ;)
