### ISSUE TITLE
[webOS 3.4.0] Halts on Stage 1

### ISSUE THREAD

**Issue by Informatic** [RootMyTV/RootMyTV.github.io#21]
As reported on Discord
> Connected apps enabled, prompts to install, tries to launch app but gets stuck in gray loading screen, then reboots.

**Comment by Juanfragar** [comment]
My report, more info:
Status: Not working
TV Model: 65UH625V-ZA
webOS Version: 3.4.0-5805 (dreadlocks-digya)
Software Version: 05.60.15 (latest by lg)


This is the result when accessing http://dropbox.inf.re/webos-downgrade/ 

![IMG_2137](https://user-images.githubusercontent.com/2629543/149593486-f492baec-def6-4b87-a320-fab3401a72b2.jpg)

**Comment by Informatic** [comment]
Could you please also *try* capturing which apps it tries to launch? Last log line before it shows a splash screen.

**Comment by Juanfragar** [comment]
It finds both com.webos.app.facebooklogin and com.webos.app.acrcard
Tries to launch com.webos.app.acrcard

**Comment by Informatic** [comment]
Fixed.
