### ISSUE TITLE
error 113

### ISSUE THREAD

**Issue by JonnyTech** [RootMyTV/RootMyTV.github.io#23]
When browsing to rootmy.tv on my tv browser:

`error 113 (net::err_ssl_version_or_cipher_mismatch): unknown error`

Model/Type: 42LA602V-ZA
Software version: 04.28.17
SDK Version: 03.05

Date and time are correct.
No updates available.

Is there a workaround?

**Comment by smx-smx** [comment]
That is a Netcast TV, which is not supported by RootMyTV.
There are different methods for Netcast. Join the Discord channel for more details

**Comment by JonnyTech** [comment]
Ah, as it had webos I thought it was supported. Thanks for the clarification.
