### ISSUE TITLE
Feature Request: App to install/use color profiles or save the existing one

### ISSUE THREAD

**Issue by blitmap** [RootMyTV/RootMyTV.github.io#26]
Hello!

I'm new to this.  I used this on an OLED LG TV.  Definitely bought this for great/accurate color reproduction.  My understanding is while I have my computer hooked up to the TV I can certainly use a custom color profile installed on the computer.

If there's room for ideas: I would suggest creating an app to use a custom color profile when using the TV standalone.  I believe ICC profiles are a standard file format for this description.  Color calibrators sometimes save color settings as a file that could then be consumed by this app (in theory).

I absolutely understand this is a volunteer project and am very thankful for the existing work done here.  I love the DVD screensaver and adfree YouTube, and I'm looking at getting my collections of ROMs up to use the RetroArch app :-)

(Thank you!)

**Comment by mariotaku** [comment]
Better place for mods/app idea would be [here](https://github.com/webosbrew/apps-repo/issues/new/choose) You are welcomed to suggest ideas :)
