### ISSUE TITLE
Is it possible to change settings in the service menu?

### ISSUE THREAD

**Issue by fulalas** [RootMyTV/RootMyTV.github.io#33]
I wonder now that you guys (geniuses!) managed to root these TVs if it's possible to change some settings only available under the service menu (which requires a special remote control).

Linus Tech Tips made a video on how to disable TPC, which dims the screen when it detects static images for more than x seconds: https://youtu.be/hWrFEU_605g?t=577

It would be really nice to be able to change that without having to buy this special remote control :)

Thanks for the hard work!

**Comment by Informatic** [comment]
Yes, it is perfectly possible to launch service menus, both [with root](https://www.webosbrew.org/pages/commands-cheatsheet.html#factorywin-app-ezadjustinstartinstop), or even without - go to this page in webOS system browser - https://dropbox.inf.re/webos-downgrade/ (ignore `downgrade` part - it's just my tooling experimentation page), accept connection prompt, then press "ezAdjust" or "inStart" button at the bottom of the page (depending on where your options are).

PIN is 0413.

No warranty, yadda, yadda.

**Comment by fulalas** [comment]
Wonderful! It was under inStart and it worked like a charm. Thanks a lot!

Off-topic: is there a way to get rid of that '3 months free blahblahblah' popup when we turn on the TV?

**Comment by Informatic** [comment]
Yes. Getting the TV off internet completely, or blocking `REGION.lgtvsdp.com` domain on your local DNS server. See for some reference on issues that may come up when doing this: https://github.com/RootMyTV/RootMyTV.github.io/issues/19#issuecomment-1013349909
