### ISSUE TITLE
SSH credentials?

### ISSUE THREAD

**Issue by BLISSEON** [RootMyTV/RootMyTV.github.io#37]
Hi!

Maybe I didn't read correctly, but you mention that "alpine" is the default SSH password. But... What is the username?

I tried various things to login with "alpine" as a password but I always get a "permission denied" error... Can you help me please?

**Comment by Informatic** [comment]
"If you need remote root shell access and know how to use SSH[...]" - so that's a password for `root` user. Probably need to rephrase it somehow.

**Comment by BLISSEON** [comment]
Why didn't I think of this! Thank you so much Sir!
