### ISSUE TITLE
How to get rid of 'Failsafe mode! Open telnet and remove /var/luna/preferences/webosbrew_failsafe'?

### ISSUE THREAD

**Issue by fulalas** [RootMyTV/RootMyTV.github.io#42]
QuickStart is already enabled.

![1](https://user-images.githubusercontent.com/27843666/164133430-86fc6f39-10f4-44e7-aeb7-4eb357514c6f.jpg)

**Comment by Informatic** [comment]
https://github.com/RootMyTV/RootMyTV.github.io#i-quickly-turned-my-tv-on-and-off-and-its-really-angry-about-failsafe-mode

Then, go to Homebrew Channel → Apps list → Homebrew Channel → Update, then launch Homebrew Channel again - this will update some startup scripts to alleviate certain cases of failsafe mode tripping too early.

**Comment by fulalas** [comment]
Thanks!
