### ISSUE TITLE
I can’t connect LGTV via PC

### ISSUE THREAD

**Issue by usernoobguy** [RootMyTV/RootMyTV.github.io#43]
Hi, days ago I rooted my leg tv and it work, and I need a tool called Magic4pc to use my tv magicstick to control my pc, but I don’t know how to connect my pc and tv on same internet, I tried CLI tool u can see on pictures.
Btw, thx for helping !
![632165D1-A104-4F6C-95DA-0C22F6892178](https://user-images.githubusercontent.com/99551629/168106495-07fd5da0-7c39-43d0-b0f9-280e3f4ea6ce.jpeg)
![7ED6B03A-8C2D-4FC7-9FC1-006AAD26A2BF](https://user-images.githubusercontent.com/99551629/168106536-e97a2ed4-b229-4733-89d7-a6c13ea42ca1.jpeg)
![603CBE28-08F6-4D9C-B590-B448D5E9A06E](https://user-images.githubusercontent.com/99551629/168106539-adb2db9e-7606-4ac3-8a38-dd625ae798a9.jpeg)
![534B1DF4-0860-4A76-BEC0-0CD4283A93D7](https://user-images.githubusercontent.com/99551629/168106542-747abc8c-25ad-4515-b57f-530dac6a1e2a.jpeg)

**Comment by tuxuser** [comment]
Hi!

Please follow these instructions to use the WebOS ask tools with rooted TV: https://www.webosbrew.org/pages/configuring-sdk.html#configuring-webososeares-cli-with-rooted-tv

**Comment by tuxuser** [comment]
No, no need for the developer mode app, having root and enabled SSH in Homebrew Channel is enough to follow the instructions on the website.
You just have to follow the instructions I posted. If you have trouble at a particular step, please write which and we will try to help.

**Comment by usernoobguy** [comment]
> No, no need for the developer mode app, having root and enabled SSH in Homebrew Channel is enough to follow the instructions on the website.
> You just have to follow the instructions I posted. If you have trouble at a particular step, please write which and we will try to help.

I’m already enable ssh key server in homebrew channel, but I have no idea how to generate a ssh key on ”developer machine”(my pc or tv?), and what is the step3 for ?  Do I need to explore tv file? Sorry I’m not professional at this part😭

**Comment by tuxuser** [comment]
Developer machine is your PC. What kind of operating system do you use?

Google "ssh keygen Windows/Linux/WebOS" depending on your OS. After generating a keypair, you copy the key with ".pub" suffix to your TV, according to the instructions.

**Comment by tuxuser** [comment]
Use the following command in git bash:

```ssh-copy-id root@ip-address-of-TV```

Password: `alpine`

**Comment by usernoobguy** [comment]
> 

Message shows: mkdir: can't create directory '/etc/dropbear': Read-only file system 
after i enter password

**Comment by tuxuser** [comment]
Copy & paste this command, after modifying `ip-address-of-TV` again:

```
ssh root@ip-address-of-TV "mkdir /home/root/.ssh; echo $(cat ~/.ssh/id_rsa.pub) > /home/root/.ssh/authorized_keys"
```

**Comment by usernoobguy** [comment]
> Copy & paste this command, after modifying `ip-address-of-TV` again:
> 
> ```
> ssh root@ip-address-of-TV "mkdir /home/root/.ssh; echo $(cat ~/.ssh/id_rsa.pub) > /home/root/.ssh/authorized_keys"
> ```
> 
> After that, you should be able to do `ssh root@ip-address-of-TV` without it promting you for a password.
> 
> mission success!

@tuxuser omg it works! tux u are saviour.
![未命名](https://user-images.githubusercontent.com/99551629/168164576-fa2c25c2-6dc8-4fde-aa14-9cfafe44ef72.png)
btw, should i ignore the message, do i need insert an new key again? or there is noting i need to do now.

**Comment by tuxuser** [comment]
The warning will be gone after a reboot of the TV.
It will automatically detect that a public key is available and disable password authentication.

PS: Don't lose your SSH keypair ;)

Is the issue solved, everything cool?

**Comment by usernoobguy** [comment]
> The warning will be gone after a reboot of the TV. It will automatically detect that a public key is available and disable password authentication.
> 
> PS: Don't lose your SSH keypair ;)
> 
> Is the issue solved, everything cool?

Yes! @tuxuser thank for your patience, sorry i took you so much time on this. Also, thx to community to make this powerful and amazing tool. :D

**Comment by tuxuser** [comment]
You are welcome :)
Please close the issue, as it's solved now.
