### ISSUE TITLE
WebSocket connection failure

### ISSUE THREAD

**Issue by Informatic** [RootMyTV/RootMyTV.github.io#5]
```
Status: working
TV Model: 32LJ600B-SA
webOS Version: 3.8.0-61409 (dreadlocks2-dunggir)
Software Version: 05.80.40

an update later...

Status: not working (asks if LG Connect Apps is enabled)
TV Model: 32LJ600B-SA
webOS Version: 3.9.0-63004 (dreadlocks2-dudhwa)
Software Version: 06.00.04
```

_Originally posted by @SergioVJr in https://github.com/RootMyTV/RootMyTV.github.io/issues/2#issuecomment-860275219_

This sounds quite interesting.

Could you please elaborate on that a little bit? Have you taken a look at [`docs/TROUBLESHOOTING.md`](https://github.com/RootMyTV/RootMyTV.github.io/blob/acd073ad754f4635c97efd5145129095403ae509/docs/TROUBLESHOOTING.md)?
Did you make sure LG Connect Apps is enabled in settings, and that the TV responds on http://localhost:3000?

**Comment by SergioVJr** [comment]
I tried it again and now it's working, I'll update the status on that issue. I had tried it right after updating, had made sure LG Connect Apps was enabled in settings, and tried disabling it and enabling again. Maybe i just needed to turn the TV off and on again.

**Comment by Informatic** [comment]
Thanks, closing it then. Will add a hint to reboot a TV when troubleshooting later.
