### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by maix-me** [RootMyTV/RootMyTV.github.io#52]
Can I somehow upgrade now on a non-rooted TV?
When I try to open the rootmy.tv site, I get a certificate error 113. And the site does not open

**Comment by DavidBuchanan314** [comment]
1) Is the date and time on your TV set correctly?

2) What model and webos version is your TV running?

**Comment by maix-me** [comment]
Is the date and time on your TV set correctly? - Yes

What model and webos version is your TV running? - I don't know which version webos:
04.28.17
03.05
V6.00.00.7dd4d2.4960
36AC9E2

**Comment by maix-me** [comment]
TV Model - 27mt75s-pqz
04.28.17 - Softvare version
03.05 - SDK version
V6.00.00.7dd4d2.4960 - Browser version
36AC9E2 - VSN

**Comment by DavidBuchanan314** [comment]
This TV is almost certainly too old to be compatible with rootmy.tv, I'm not sure it's even running webOS at all. You might have luck with this: https://forum.xda-developers.com/t/getmein-one-time-rooting-jailbreaking-tool-for-webos-lg-tvs.3887904/page-6
