### ISSUE TITLE
Creating a systemd service

### ISSUE THREAD

**Issue by chcore** [RootMyTV/RootMyTV.github.io#59]
How do I go about making my own systemd service? If I drop a .service file in `/home/root/.config/systemd/user` and try a `systemctl --user daemon-reload` or `systemctl --user start testing.service` I just get a `Failed to connect to bus: No such file or directory`.

I cannot write to `/etc/systemd/system` either, as I just get the error `Read-only file system`, even after a `mount -o rw,remount /`.

Is this at all possible? Thank you for this project

**Comment by Informatic** [comment]
webOS does not support systemd user session daemon. You can try adding a
system unit by creating an overlay over /etc/systemd as described here:
https://www.webosbrew.org/pages/filesystem-overlays.html#adding-files-to-an-existing-directory

Keep in mind systemd is only present on webOS 4+ (if I remember correctly),
if you plan to make some reusable homebrew/guide. On 3.x and older upstart
is used for system services.

**Comment by chcore** [comment]
Thank you @Informatic, I didn't know about OverlayFS. That worked perfectly.
