### ISSUE TITLE
Denied method call

### ISSUE THREAD

**Issue by komOrmand** [RootMyTV/RootMyTV.github.io#7]
Hi!
Recieved this error, connected apps are turned on.

![photo_2021-08-11_22-02-43](https://user-images.githubusercontent.com/87458360/129088016-2e056032-d3be-43b0-abb7-5ca307b05f48.jpg)

Firmware:
![photo_2021-08-11_22-02-43 (2)](https://user-images.githubusercontent.com/87458360/129088072-383f4aaa-4339-4570-bd76-94fd5da5c32b.jpg)

**Comment by Yasich217** [comment]
05.10.25 FW with error

**Comment by RenderMeWell** [comment]
Same problem UK6500 FW 05.40.20. Should I update the webos?

**Comment by Kozikodi** [comment]
> 05.10.25 FW with error
> I downgraded firmware to 05.00.10 and it worked

Any hints on how to downgrade?

**Comment by nox26** [comment]
Im also on 05.10.25.. how can I downgrade firmware? Any hints ? Thanks

**Comment by atomas42** [comment]
LG 55C97LA 05.10.25 same Problem

**Comment by Yasich217** [comment]
Downgrade tutorial http://webos-forums.ru/post138776.html#p138776

**Comment by PinkyJie** [comment]
Same error on `05.20.06`.

**Comment by PinkyJie** [comment]
Thanks for @Yasich217 's link above, I was finnally able to downgrade my TV and got it rooted.
The original link is in Russian language, you can just use Google Translate to translate to your native language.

**Comment by DpunktKpunkt** [comment]
FW collection for almost every webOS TV: http://webos-forums.ru/post23624.html#p23624

**Comment by Informatic** [comment]
PSA: RootMyTV v2 release is planned for around 2022/01/14 18:00 UTC (this Friday)

This will be compatible with all current webOS versions between 3.4 and 6.2 (up to the latest released ones), and shall alleviate any issues reported here.

**Comment by DpunktKpunkt** [comment]
Now everybody should download the current firmware version so you can downgrade to that specific fw - just in case LG is fixing the new vulnerability RootMyTV v2 uses.

**Comment by armandoi75** [comment]
> Now everybody should download the current firmware version so you can downgrade to that specific fw - just in case LG is fixing the new vulnerability RootMyTV v2 uses.

Do you have a direct link where to download all the lg firmware files?
Thanks a lot

**Comment by armandoi75** [comment]
> > Now everybody should download the current firmware version so you can downgrade to that specific fw - just in case LG is fixing the new vulnerability RootMyTV v2 uses.
> 
> Do you have a direct link where to download all the lg firmware files? Thanks a lot

Let me answer to myself: https://t.me/lgwebosusb
;-)

Thanks anyway

**Comment by Informatic** [comment]
RootMyTV v2 is out now.
