### ISSUE TITLE
Magic Remote IR Blaster Remapping

### ISSUE THREAD

**Issue by maxexcloo** [RootMyTV/RootMyTV.github.io#79]
When setting up external devices it's possible to control sound bar volume and such via the IR blaster in the magic remote - the problem I'm facing is my new soundbar isn't listed in the options like my old one was. Wondering if anyone has any knowledge of adding new IR codes/manufacturers to the database.

**Comment by coolfizzin** [comment]
What's your soundbar? You might discover that its codes are similar to another device that is already listed.
