### ISSUE TITLE
Not compatible with webOS 22

### ISSUE THREAD

**Issue by ThorsOdin** [RootMyTV/RootMyTV.github.io#91]
Bought a new TV, wanted some apps not currently supported within the onboard app store, tried to root once unsuccessfully then realized it was a version not mentioned in the Readme. I'll provide any other info that I can, if requested. TV model OLED77C2PUA, webOS TV version 7.2.0-44 mullet-marine.

**Comment by ThorsOdin** [comment]
Just saw the other post about webOS 7 support... delete this if needed my bad

**Comment by darccyy** [comment]
You should be able to press 'close issue' under the last comment of this post :)
